export const article_en =`<h2>An emotional human language, vocal or mechanical...</h2>
    <p>Music can be conceptually defined as a <strong>human practice</strong> with various goals and attributes. An occupation, amenity, or hobby, and one of the fine arts, but perhaps best defined as an <strong>audible language</strong> whose object of expression is <strong>emotion</strong>.</p>
    <p>Emotions such as melancholy, euphoria, serenity, mysticism, heroism, sadness, joy, tranquility, fear, resolution, expectation, etc., can be expressed or even induced by the appropriate music.</p>
    <p>An important initial consideration is that music is only produced either <strong>by some instrument</strong>, or <strong>by the voice itself</strong>.</p>
    <p>Another is that, like the faculty of speech, it is innate to us, since in some instruments it is relatively easy for us to create music, which is known as <strong>playing by ear</strong>, and <strong>singing</strong> (also <strong>by ear</strong>) comes extraordinarily naturally to us, just as we learn to speak: by imitation.</p>
    <h2>...with a grammar and written form</h2>
    <p>In addition, as a language, music has rules that form a grammar known as <strong>music theory</strong>. Most importantly, music has a written form that we call <strong>musical notation</strong> or simply <strong>notation</strong>.</p>
    <p>Fortunately, to play or sing by ear (as well as to speak) no notion about theory or notation is required, since it is often enough to have sufficient interest, tenacity and above all, a <strong>good memory</strong>. Only on the contrary, to read or write music, logically <strong>the notation is indispensable</strong>.</p>
    <p>Curiously, this fortune is not so visible at the beginning because the cryptic or enigmatic appearance of the notation makes it somewhat intimidating, although it is actually quite simple considering the following, more objective definition of music.</p>
    <h2>A more objective definition</h2>
    <p>Regardless of its language status, physically music is simply</p><p class="centered enlarged"><strong>sound</strong> organized in <strong>time</strong>,</p>
    <p>so its notation consists primarily of the symbols necessary to express the various properties and conditions of both sound and time <strong>from a musical perspective</strong>.</p>
    <p>It is precisely the simplicity of that physical nature that makes it easy to understand the basic principles of its reading and to take the first steps in that wonderful field, the subject of the following introduction, <a href="/en/notation" target="_blank"><strong>musical notation</strong></a>.</p>`;
    export const article_es = `<h2>Un emotivo lenguaje humano, vocal o mecánico...</h2>
    <p>La música puede definirse conceptualmente como una <strong>práctica humana</strong> con diversos objetivos y atributos. Una ocupación, amenidad o pasatiempo y una de las bellas artes, pero quizás se defina mejor como <strong>un lenguaje audible</strong> cuyo objeto de expresión son <strong>las emociones</strong>.</p>
    <p>Emociones como melancolía, euforia, serenidad, misticismo, heroísmo, tristeza, alegría, tranquilidad, temor, resolución, expectación, etc., son susceptibles de expresarse o incluso de inducirse mediante la música adecuada.</p>
    <p>Una importante consideración inicial es que la música sólo se produce o bien <strong>con algún instrumento</strong>, o bien <strong>con la propia voz</strong>.</p>
    <p>Otra es que, al igual que la facultad del habla, nos es innata, pues en algunos instrumentos nos resulta fácil crear música, lo que se conoce como <strong>tocar de oído</strong>, y el <strong>cantar</strong> (también <strong>de oído</strong>) se nos da de manera extraordinariamente natural, igual a como aprendemos a hablar: por imitación.</p>
    <h2>...con una gramática y forma escrita</h2>
    <p>Además, como lenguaje, la música tiene reglas que configuran una gramática conocida como <strong>teoría musical</strong>. Y lo más importante, la música cuenta con una forma escrita a la que llamamos <strong>notación musical</strong> o simplemente <strong>notación</strong>.</p>
    <p>Por fortuna, para tocar o cantar de oído (así como para hablar) es innecesaria noción alguna sobre teoría o notación, pues a menudo es suficiente con tener suficiente interés, tenacidad y sobre todo, <strong>buena memoria</strong>. Sólo que por el contario, para leer o escribir música, lógicamente <strong>la notación resulta indispensable</strong>.</p>
    <p>Curiosamente, esa fortuna no es tan visible al principio pues la apariencia críptica o enigmática de la notación la hace algo intimidante, aunque en realidad resulta bastante sencilla considerando la siguiente definición, más objetiva, de la música.</p>
    <h2>Una definición muy simple pero objetiva</h2>
    <p>Independientemente de su condición de lenguaje, físicamente la música es simplemente</p>
    <p class="centered enlarged"><strong>sonido</strong> organizado en el <strong>tiempo</strong>,</p>
    <p>por lo que su notación consiste primordialmente de los símbolos necesarios para expresar las diversas propiedades y condiciones tanto del sonido como del tiempo <strong>desde una perspectiva musical</strong>.</p>
    <p>Es precisamente la sencillez de esa naturaleza física lo que permite comprender fácilmente los principios básicos de su lectura y dar los primeros pasos en ese maravilloso terreno, tema de la siguiente introducción, <a href="/es/notacion"><strong>notación musical</strong></a>.</p>`;