export const article_en =`<h2>The written word and music</h2>
    <p>There is no doubt that singing is a faculty of ours as innate as speech, but reading both the written word and <strong>musical notation</strong>, the formal name for musical writing, require <strong>special learning processes</strong>.</p>
    <p>The process of learning to read the written word is known as <strong>literacy</strong>, so learning to read notation may very well be regarded as <strong>becoming musically literate</strong>.</p>
    <p>However, it might well be thuoght that of these two processes, learning to read music might be the easier and quicker.</p>
    <h2>Difficult to read musical notation? Let's see</h2>
    <p>An encouraging feature in favor of this notation is that despite its intimidating appearance the names of the sounds, formally <strong>notes</strong>, are only <strong>seven</strong> and their durations or basic <strong>values</strong> used <strong>rarely more than five</strong>, while the written word uses more than two dozen letters and a many, many combinations, although the timing and rhythm are extremely flexible.
    </p>
    <p>Another, particular to <strong>Doremitutor</strong>, is the omission of the usual initial presentations of needless and somewhat complex categories of concepts, except those strictly essencial for gradual and focused progress. Only one step at a time.</p>
    <p>And one more is that, however indescribable its appearance and the number of symbols it uses, in essence musical notation simply <strong>describes the passage of time and the notes to be played or sung</strong>.</p>
    <p>According to this, we can conclude that reading music can basically be reduced to <strong>playing or singing each written note at the right time and for the right duration</strong>, which requires the precise interpretation of the corresponding symbols.</p>
    <p>As for time, its measurement becomes intuitive easily because it only requires basically counting up to <strong>two</strong>, <strong>three</strong> or <strong>four</strong> pulses (<strong>beats</strong>, in musical language), and their groupings and subdivisions. Its mastery is a matter of practice. Nothing at all to worry about, that subject is explored in detail in the section on <a href="/en/theory/time/beat-and-metronome" target="_blank"><strong>time</strong></a>.</p>
    <p>It is in relation to sound that a fundamental difference appears that depends on the purpose of the reading:</p>
    <h2>Notation can be played or sung</h2>
    <p>To play most instruments, reading only requires becoming familiar with them to make them generate the notes read, an essentially mechanical process called <strong>playing by note</strong>, but singing written music, known as <strong>sight singing</strong>, <strong>solfége</strong>, or <strong>solfeggio</strong>, is a little (or noticeably) more complicated. because it requires a very particular additional faculty that we will address in the next presentation, <a href=""><strong>sight singing</strong></a>.</p>
    <p>To play some instruments, reading notation may only require learning to make them generate the notes read, that is, <strong>sight reading</strong>, but singing written music, known as <strong>sight singing</strong>, <strong>solfège</strong>, or <strong>solfeggio</strong> is notably more complicated as it requires a very particular additional skill that we will address in the following presentation, <a href="/en/sight-singing"><strong>sight singing</strong></a>.</p>
    `;
    export const article_es = `
    <h2>La música y la palabra escritas</h2>
    <p>Es indudable que el canto es una facultad nuestra tan innata como el habla, pero la lectura tanto de la palabra escrita como de la <strong>notación musical</strong>, nombre formal de la escritura musical, requieren <strong>procesos particulares de aprendizaje</strong>.</p>
    <p>El proceso de aprender a leer la palabra escrita se conoce como <strong>alfabetización</strong>, por lo que aprender a leer notación musical muy bien puede considerarse como <strong>alfabetizarse musicalmente</strong>.</p>
    <p>Sin embargo, bien podría pensarse que de estos dos procesos, aprender a leer música podría ser el más fácil y rápido.</p>
    <h2>¿Difícil leer notación? ¡Si son sólo <strong>siete</strong> notas!</h2>
    <p>Un rasgo alentador a favor de esta notación es que a pesar de su aspecto intimidante los nombres de los sonidos, formalmente <strong>notas</strong>, sólo son <strong>siete</strong>, y sus duraciones o <strong>valores</strong> básicos usados <strong>rara vez más de cinco</strong>, mientras que la palabra escrita utiliza más de <strong>dos docenas de letras y muchísimas combinaciones</strong>, aunque el tiempo y ritmo son sumamente flexibles.</p>
    <p>Otro, particular de <strong>Doremitutor</strong>, es la omisión de las acostumbradas presentaciones iniciales de innecesarias y algo complicadas categorías de conceptos, <strong>salvo los estrictamente esenciales</strong> para un progreso gradual y enfocado. Únicamente un paso a la vez.</p>
    <p>Y uno más es que con todo y lo indescrifrable de su apariencia y la cantidad de símbolos que utiliza, en esencia la notación musical simplemente <strong>describe el transcurso del tiempo y las notas a tocar o cantar</strong>.</p>
    <p>De acuerdo a esto, podemos concluir que leer música puede reducirse básicamente a <strong>tocar o cantar cada nota escrita en el momento indicado y por la duración correcta</strong>, lo que requiere la interpretación precisa de los símbolos correspondientes.</p>
    <p>En cuanto al tiempo, su medición se vuelve intuitiva fácilmente pues sólo requiere básicamente de contar hasta <strong>dos</strong>, <strong>tres</strong> o <strong>cuatro</strong> pulsos (<strong>tiempos</strong>, en lenguaje musical), y sus <strong>agrupaciones</strong> y <strong>subdivisiones</strong>. Su dominio es cuestión de <strong>práctica</strong>. Nada en absoluto de qué preocuparse, ese tema se explora en detalle en la sección del <a href="/es/teoria/tiempo/tiempo-y-metronomo" target="_blank"><strong>tiempo</strong></a>.</p>
    <p>Es en relación al sonido donde aparece una diferencia fundamental que depende del propósito de la lectura:</p>
    <h2>La notación puede tocarse o cantarse</h2>
    <p>Para tocar algunos instrumentos, leer notación puede requerir sólo aprender a hacerlos generar las notas leídas, es decir, <strong>tocar por nota</strong>, pero el canto de la música escrita, conocido como <strong>solfeo</strong>, es notablemente más complicado pues requiere de una habilidad adicional muy particular que abordaremos en la siguiente presentación, <a href="/es/solfeo"><strong>el solfeo</strong></a>.</p>`;