export const article_en=`
    <p>Music offers multiple fields of incredible interest such as harmony, counterpoint, orchestration, composition, and many more whose full understanding <strong>requires to read music</strong>, and it is <strong>Doremitutor</strong>'s intention to contribute to the achievement of this objective for anyone interested through <strong>attractive, audiovisual</strong>, and above all, <strong>interactive didactic material</strong>.</p>
    <h2>Who is this site for?</h2>
    <p>This site is aimed at three categories of users:</p>
    <ol>
        <li>Those interested in learning, from scratch and without unnecessary theoretical complications, to <strong>read written music</strong> and even sing it with precision, this latter practice known as <strong>sight singing</strong> or <strong>solfeggio</strong>, who can take the first steps in this <a href="/en/music" target="_blank"><strong>introduction to music</strong></a>.</li>
        <li>Those already initiated in instrumental reading interested in <strong>developing</strong>, <strong>exercising</strong> or <strong>improving</strong> their sight singing.</li>
        <li>More advanced players or solfists interested in practicing or extending their sight singing in scales with up to <strong>three sharps</strong> or <strong>flats</strong>.</li>
    </ol>
    <p>Users in these two last categories, perhaps more interested in the exercises, are encouraged to read the <a href="/en/player" target="_blank"><strong>introduction to the player</strong></a> as a preparation to select their favorite material, whether in <a href="/en/basic-sight-singing/treble-clef/c/tonic-two-four" target="_blank"><strong>treble</strong></a> or <a href="/en/basic-sight-singing/bass-clef/c/tonic-two-four" target="_blank"><strong>bass</strong></a> clef.</p>
    <h2>The necessary theory in animations</h2>
    <p>Fortunately, the initial learning of sight singing only requires some very simple ideas, which are presented through <strong>interactive audiovisual animations</strong> conveniently explained.</p>
    <p>This simplified theory is presented in three sections following the introductions (of which this one is the first) corresponding to the basic concepts of <a href="/en/theory/sound/note-pitch-scale" target="_blank"><strong>sound</strong></a>, <a href="/en/theory/time/beat-and-metronome" target="_blank"><strong>time</strong></a> and <a href="/en/theory/notation/staff-and-basic-note" target="_blank"><strong>notation</strong></a>, for newbies or interested in reviewing the fundamental ideas.</p>
    <h2>A relief for the dreaded exercises</h2>
    <p>Learning solfeggio involves performing multiple repetitions of reading exercises, which <strong>Doremitutor</strong> facilitates with <a href="/en/player" target=_blank><strong>this player</strong></a> that presents them <strong>visually</strong>, <strong>aurally</strong>, and <strong>interactively</strong> under the full control of the user (<strong>you</strong>), turning what in the past has often been considered tedious into an entertainment that is as edifying as it is pleasing.</p>
    <p>At this beginning, two series of <strong>basic sight singing exercises</strong> are presented, one in <a href="/en/basic-sight-singing/treble-clef/c/tonic-two-four" target="_blank"><strong>treble clef</strong></a> and the other in <a href="/en/basic-sight-singing/bass-clef/c/tonic-two-four" target="_blank"><strong>bass clef</strong></a>. Each series consists of <strong>48</strong> of these, but in <strong>seven scales or tonalities each</strong>, which makes <strong>672</strong> of them, to be explained at the time, for the benefit of those who wish to explore its advanced forms.</p>
    <h2>Some relaxation</h2>
    <p>Of course, there is also entertainment, of which the first examples are the <strong>Notehunter</strong>s, a couple of applications to learn or review by playing the names of the notes on the staff (actually all the applications are somewhat entertaining).</p>
    <h2>There is no return of your money, but there is some guarantee - Some history</h2>
    <p>The initial versions of the site disappeared due to problems with <strong>Java</strong>, the only suitable language at that time to write the applications, but the written music theory classes were published as videos on the <a href="https://www.youtube.com/@doremitutor_en" target="_blank"><strong>YouTube.com/doremitutor</strong></a> channel, with surprising user acceptance. <strong>That is precisely the guarantee</strong>.</p>
    <h2>Doremitutor has been able to return, but requires support to grow</h2>
    <p>Finally, the site reappears with the same and other applications now written in <strong>Javascript</strong> for today's web. However, projects like this require resources to sustain and develop, so any contributions from those who find it valuable will have my gratitude and surely that of those who cannot contribute.</p>
    <p>It is my firm claim and commitment to continue producing musical educational material as long as <strong>The Creator</strong> allows me to share it, either in videos for the channel or applications for the site. It will be an honor to continue to be your tutor. Affectionately,</p>
    <p class="signature">Jesús Díaz Rodríguez.</p>`;
export const article_es = `
    <p>La música ofrece múltiples campos de increíble interés como armonía, contrapunto, orquestación, composición y muchos más cuya comprensión cabal <strong>requiere leer música</strong>, y es intención de <strong>Doremitutor</strong> contribuir al alcance de este objetivo para cualquier interesado mediante <strong>atractivo material didáctico audiovisual</strong>, pero sobre todo, <strong>interactivo</strong>.</p>
    <h2>¿Para quién es este sitio?</h2>
    <p>Este sitio está orientado a tres categorías de usuarios:</p>
    <ol>
        <li>Aquellos interesados en aprender, <strong>desde cero</strong> y sin complicaciones teóricas, a <strong>leer música escrita</strong> e incluso cantarla con precisión, práctica esta última conocida como <strong>solfeo</strong>, a quienes para dar los primeros pasos se recomienda iniciar con la <a href="/es/musica" target="_blank"><strong>introducción a la música</strong></a>.</li>
        <li>Los ya iniciados en la lectura instrumental interesados en <strong>desarrollar</strong>, <strong>ejercitar</strong> o <strong>perfeccionar</strong> su solfeo,</li>
        <li>Lectores o solfistas ya experimentados interesados en practicar o extender su solfeo a escalas con hasta <strong>tres sostenidos</strong> o <strong>bemoles</strong>.
       </li>
    </ol>
     <p>Para usuarios avanzados en estas dos últimas categorías, más interesados en los ejercicios, se recomienda la introducción al <a href="/es/reproductor" target="_blank"><strong>reproductor</strong></a> como preparación para elegir y ejecutar sus ejercicios en <a href="/es/solfeo-basico/clave-sol/c/tonica-dos-por-cuatro" target="_blank"><strong>clave de Sol</strong></a>, o <a href="/es/solfeo-basico/clave-fa/c/tonica-dos-por-cuatro" target="_blank"> <strong>clave de Fa</strong></a>.</p>
    <h2>La necesaria teoría en animaciones</h2>
    <p>Por fortuna, el aprendizaje inicial del solfeo únicamente requiere de algunas ideas muy simples, mismas que son presentadas mediante <strong>animaciones audiovisuales interactivas</strong> convenientemente explicadas.</p>
    <p>Esta teoría simplificada se presenta a continuación de las introducciones (de las que ésta es la primera) en tres secciones correspondientes a los conceptos básicos de <a href="/es/teoria/sonido/nota-tono-escala" target="_blank"><strong>sonido</strong></a>, <a href="/es/teoria/tiempo/tiempo-y-metronomo" target="_blank"><strong>tiempo</strong></a> y <a href="/es/teoria/notacion/pentagrama-y-nota-basica" target="_blank"><strong>notación</strong></a>, para los interesados novicios o en repasar las ideas fundamentales.</p>
    <h2>Un alivio para los temidos ejercicios</h2>
    <p>Aprender solfeo implica realizar múltiples repeticiones de ejercicios de lectura, lo que <strong>Doremitutor</strong> facilita con <a href="/es/reproductor" target="_blank"><strong>este reproductor</strong></a> que los presenta <strong>visual</strong>, <strong>auditiva</strong> e <strong>interactivamente</strong> bajo el control total del usuario (<strong>usted</strong>), convirtiendo lo que en el pasado a menudo se ha considerado tedioso en un entretenimiento tan grato como edificante.</p>
    <p>En este inicio, se presentan dos series de <strong>ejercicios básicos de solfeo</strong>, una en <a href="/es/solfeo-basico/clave-sol/c/tonica-dos-por-cuatro" target="_blank"><strong>clave de Sol</strong></a> y otra en <a href="/es/solfeo-basico/clave-fa/c/tonica-dos-por-cuatro" target="_blank"><strong>la de Fa</strong></a>. Cada una consta de <strong>48</strong> de estos ejercicios, pero en <strong>7 escalas</strong> o <strong>tonalidades</strong> cada uno, lo que totaliza <strong>672</strong> de ellos, explicados al presentarlos, para beneficio de quienes deseen explorar sus formas avanzadas.</p>
    <h2>Algo de esparcimiento</h2>
    <p>Por supuesto, también hay entretenimiento, del que las primeras muestras son <a href="/es/juegos/cazanotas/cazanotas-clave-sol" target="_blank"><strong>los Cazanotas</strong></a>, un par de juegos para aprender o repasar los nombres de las notas en el pentagrama (en realidad todas las aplicaciones tienen algo de entretenidas).</p>
    <h2>No hay devolución de su dinero, pero sí hay alguna garantía - Algo de historia</h2>
    <p>Las primeras versiones de este sitio desaparecieron por inconvenientes con <strong>Java</strong>, único lenguaje adecuado en esos inicios para escribir las aplicaciones, pero las clases de solfeo escritas fueron publicadas como videos en el canal <a href="https://youtube.com/doremitutor" target="_blank"><strong>YouTube.com/doremitutor</strong></a>, y sorprendentemente aceptadas por los usuarios. <strong>Ésa es precisamente la garantía</strong>.</p>
    <h2>Doremitutor ha podido regresar, pero requiere apoyo para crecer</h2>
    <p>Finalmente, el sitio reaparece con las mismas y otras aplicaciones escritas ahora en <strong>Javascript</strong> para la web actual. Sin embargo, proyectos como éste requieren recursos para sostenerse y desarrollarse, por lo que cualquier aportación de quien lo encuentre valioso contará con mi gratitud y seguramente la de quienes no puedan contribuir.</p>
    <p>Es mi firme pretensión y compromiso continuar produciendo material educativo musical mientras <strong>El Creador</strong> me lo permita para compartirlo, ya sea en videos para el canal o aplicaciones para el sitio. Será un honor el continuar siendo su tutor. Afectuosamente,</p>
    <p class="signature">Jesús Díaz Rodríguez.</p>
    <p>Pero entremos en materia y veamos, <a href="/es/musica"><strong>¿qué es la música?</strong></a></p>`;