export const article_en = `<h2>Playing by note and sight singing (solfège)</h2>
    <p>One form of reading notation consists of just associating the written notes with their playing on <strong>fixed-note instruments without anticipating their tone</strong>, which is known as <strong>sight reading</strong>, or to pronounce their names on time and for the correct durations but <strong>without singing them</strong>.</p>
    <p>But reading music for playing <strong>variable-note instruments</strong> like violin, slide trombone, double bass, etc., or <strong>singing it</strong> and even <strong>reading it mentally</strong> requires the additional skill to interpret <strong>certain auditory content of the notes</strong> to ensure their accuracy in playing, singing or evoking them.</p>
    <p>This type of musical reading, <strong>mentally</strong> or <strong>sung</strong> instead of or in addition to being <strong>performed instrumentally</strong>, is formally known as <strong>sight singing</strong>, <strong>solfège</strong>, or <strong>solfeggio</strong>, which learning requires recognizing and developing a <strong>little understood ability</strong> to grasp that mentioned auditory or tonal content, an indispensable faculty in all serious musical training.</p>
    <h2>A fully developed but misunderstood sense...</h2>
    <p>It is about that ease with which we remember, sing and recognize tunes and even complete works. That amazing capacity to perceive, remember and evoke that subtle content. Capacity that once <strong>recognized</strong>, <strong>studied</strong> and <strong>systematized</strong>, allows us to perceive and understand music with incredible clarity never before imagined.</p>
    <p>A most important clarification is that this content is completely different from the particular <strong>tone</strong> or <strong>pitch</strong> of each individual note, whose precise identification is relatively irrelevant.</p>
    <h2>...who perceives a sensation as manifest as it is unnoticed</h2>
    <p>Instead, this tonal content is a property that each note acquires only <strong>in a sequence of several of them</strong>, a particular auditory sensation that depends on the relationship between its tone and that of the others, <strong>a sensation whose recognition is the key to sight singing</strong>. This sensation is known as <strong>tonal tension</strong>.</p>
    <p>And it is so natural to us that we perceive, remember and replicate it naturally, spontaneously, instinctively, and unconsciously. Its <strong>conscious perception and expression</strong> only become relevant if we take a <strong>serious interest in music</strong>.</p>
    <p>And it is extraordinarily important because what allows us to solfège is to identify that tension in the notes and not their names, because the notes <strong>can be changed by others</strong> preserving the idea <strong>as long as the relationships between their tensions remain constant</strong>. This is why we remember melodies easily <strong>although not in their original pitch</strong>.</p>
    <h2>But fortune is limited...</h2>
    <p>What is no longer so fortunate for those really interested is that in order to make full use of this <strong>sense of tonal tension</strong>, it is first necessary to discover and educate it, just as we learned to identify colors by their names and to associate letters with the phonemes they or their combinations represent.</p>
    <h2>...although not in Doremitutor</h2>
    <p>However, this sense is discovered and developed without much effort in <strong>Doremitutor</strong> from the first solfège lessons, because like the names of notes, there are only <strong>seven possible levels of tension</strong> (actually <strong>only six</strong>), which <strong>Doremitutor</strong> presents and describes one by one, like our first letters, assigning each one a <strong>tonal function</strong>.</p>
    <h2>Clarification: more than effort, it is entertainment</h2>
    <p>Well, actually, calling the required exercises an "effort" is an exaggeration, since each user has a personal player at his or her disposal that will make each lesson a pleasant and edifying distraction. If you don't know it yet, you can view his presentation in <a href="/en/player" target="_blank"><strong>the player</strong></a>.</p>
    <p>The following introduction, about <a href="/en/tonal-tension"><strong>tonal tension</strong></a>, describes and illustrates this concept in greater detail.</p>`;

export const article_es=`<h2>Tocar por nota y el solfeo</h2>
    <p>Una forma de lectura de notación consiste en simplemente asociar las notas escritas con su forma de tocarlas en <strong>instrumentos de notas fijas</strong> <strong>sin prever su tono</strong>, lo que se conoce como <strong>tocar por nota</strong>, o de recitar sus nombres a tiempo y por las duraciones correctas pero <strong>sin cantarlas</strong>, lo que se conoce como <strong>leer música</strong>.</p>
    <p>Pero leer música para tocar <strong>instrumentos de notas variables</strong> como el violín, trombón de vara, contrabajo, etc., o <strong>cantarla</strong> e incluso <strong>leerla mentalmente</strong> requiere la habilidad adicional de interpretar <strong>cierto contenido auditivo de las notas</strong> para asegurar su precisión al tocarlas, cantarlas o evocarlas.</p>
    <p>Este tipo de lectura musical, <strong>mental</strong> o <strong>cantada</strong> en lugar o además de <strong>ejecutada instrumentalmente</strong>, recibe el nombre formal de <strong>solfeo</strong>, cuyo aprendizaje requiere reconocer y desarrollar una <strong>poco comprendida habilidad</strong> de percibir ese contenido auditivo o tonal mencionado, <strong>facultad indispensable en toda formación musical seria</strong>.</p>
    <h2>Un sentido plenamente desarrollado pero incomprendido...</h2>
    <p>Se trata de esa facilidad con la que recordamos, cantamos y reconocemos tonadas y hasta obras completas, esa capacidad de percibir, recordar y evocar ese sutil contenido. Capacidad que una vez <strong>reconocida, estudiada y sistematizada</strong>, nos permite percibir y comprender la música con una claridad increíble jamás anteriormente imaginada.</p>
    <p>Pero es de aclarar que ese contenido es completamente diferente del <strong>tono</strong> o <strong>altura</strong> particular de cada nota en lo individual, cuya identificación precisa es relativamente irrelevante.</p>
    <h2>...que percibe una sensación tan manifiesta como inadvertida</h2>
    <p>En cambio, ese contenido tonal es una propiedad que sólo adquiere cada nota <strong>en una secuencia de varias de ellas</strong>, una sensación auditiva particular que depende de la relación entre su tono y el de las demás, <strong>sensación cuyo reconocimiento es la clave del solfeo</strong>. Esta sensación se conoce como <strong>tensión tonal</strong>.</p>
    <p>Y nos es tan natural que la percibimos, recordamos y replicamos espontánea, instintiva e inconscientemente. Su percepción y expresión <strong>conscientes</strong> sólo adquieren importancia <strong>de interesarnos seriamente en la música</strong>.</p>
    <p>Y es extraordinariamente importante porque lo que nos permite solfear es identificar esa tensión en las notas y no sus nombres, pues las notas <strong>pueden cambiarse por otras</strong> conservando la idea <strong>mientras las relaciones entre sus tensiones permanezcan constantes</strong>. Por ello recordamos  melodías fácilmente <strong>aunque no en su tono original</strong>.</p>
    <h2>Pero la fortuna es limitada...</h2>
    <p>Lo que ya no es tan afortunado para el interesado es que para utilizar cabalmente ese <strong>sentido de la tensión tonal</strong> es antes necesario <strong>descubrirlo y educarlo</strong>, justamente como aprendimos a identificar los colores por sus nombres y a asociar las letras con los fonemas que éstas o sus combinaciones representan.</p>
    <h2>...aunque no en Doremitutor</h2>
    <p>Sin embargo, ese sentido se descubre y desarrolla sin mayor esfuerzo en <strong>Doremitutor</strong> desde las primeras lecciones de solfeo, pues como los nombres de notas, <strong>sólo hay siete posibles niveles de tensión</strong> (en realidad sólo <strong>seis</strong>), que <strong>Doremitutor</strong> presenta y <strong>describe</strong> uno por uno, como nuestras primeras letras, asignándole una <strong>función tonal</strong>.</p>
    <h2>¡Aclaración!, más que esfuerzo, es entretenimiento</h2>
    <p>Bueno, en realidad atribuir "esfuerzo" a los ejercicios requeridos es una exageración, pues cada usuario cuenta con un reproductor personal a su entera disposición que hará de cada lección una amable y edificante distracción. Si aún no lo conoce, puede ver su presentación en <a href="/es/reproductor" target="_blank"><strong>el reproductor</strong></a>.</p>
    <p>La siguiente introducción, acerca de la <a href="/es/tension-tonal"><strong>tensión tonal</strong></a> describe e <strong>ilustra</strong> este concepto con mayor detalle.</p>
    <p></p>`;